### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [mooncoindev/mooncoin#5]

**Comment by slavach** [comment]
Binary doesn't work on Xenial. Should build it from source.

**Comment by ashtonhogan** [comment]
@slavach how? there are no instructions

**Comment by slavach** [comment]
See "doc/build-unix.md". Section "Dependency Build Instructions: Ubuntu & Debian".
Otherwise you can use "walletgenerator.net".

**Comment by ashtonhogan** [comment]
@slavach seems like a lot of work just to use it as a consumer

**Comment by MoNTE48** [comment]
I did it, but I did not get Mooncoin-qt!

```Making all in src```

**Comment by slavach** [comment]
@ashtonhogan agree. Too much for a customer.
